
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "FacebookAds"
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
profile : "edm_data_transformation"

vars:
  raw_database: "edm-saras" #equivalent to project_id in BigQuery
    # Example Database name
  raw_schema: "EDM_Daton" #equivalent to dataset in BigQuery
    # Example Schema name

  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0
    # Example- Daton Integration Name: Nike_US_SponsoredBrands --> Position 0, separated by '_'
  default_brandname: "" 
    # Example- default_brandname: "Nike" --> for Single Brand users, with no Brandname in Daton Integration Name
  
  get_storename_from_tablename_flag: True 
  storename_position_in_tablename: 1
    # Example- Daton Integration Name: Nike_US_SponsoredBrands --> Position 1, separated by '_'
  default_storename: "" 
    # Example- default_storename: "US" --> for Single Store users, with no Storename in Daton Integration Name

  currency_conversion_flag: False
  timezone_conversion_flag: False
  raw_table_timezone_offset_hours: {
    "Facebook.Ads.Brand_UK_Facebook_Adinsights":-7
    }

  FacebookAdinsights: True
  FacebookAdinsightsActionValues: True
  FacebookAdinsightsConversions: True
  FacebookAdinsightsConversionValues: True
  FacebookAdsByCountry: True
  FacebookAdsByProductId: True
  FacebookAdsByRegion: True
  FacebookAdsByGender: True
  FacebookAdsByGenderAge: True
  FacebookAdsByDevicePlatform: True
  FacebookAdsByPublisherPlatform: True
  FacebookAdsByPlatformPosition: True
  FacebookCampaigns: True
  FacebookAdCreatives: True
  FacebookAd: True

  fbads_creatives_tbl_ptrn: '%facebookads%ad%creatives'
  fbads_creatives_tbl_exclude_ptrn: ''
  fbads_creatives_lookback: 2952000000

  fbads_insights_tbl_ptrn: '%facebookads%ad%insights'
  fbads_insights_tbl_exclude_ptrn: ''
  fbads_insights_lookback: 2952000000

  fbads_insights_actionvalues_tbl_ptrn: '%facebookads%adinsights'
  fbads_insights_actionvalues_tbl_exclude_ptrn: ''
  fbads_insights_actionvalues_lookback: 2952000000

  fbads_insights_conversions_tbl_ptrn: '%facebookads%ad%insights'
  fbads_insights_conversions_tbl_exclude_ptrn: ''
  fbads_insights_conversions_lookback: 2952000000

  fbads_insights_conversionvalues_tbl_ptrn: '%facebookads%ad%insights'
  fbads_insights_conversionvalues_tbl_exclude_ptrn: ''
  fbads_insights_conversionvalues_lookback: 2952000000

  fbads_tbl_ptrn: '%facebookads%ads'
  fbads_tbl_exclude_ptrn: ''
  fbads_lookback: 2952000000

  fbads_by_country_tbl_ptrn: '%facebookads%adinsights%country'
  fbads_by_country_tbl_exclude_ptrn: ''
  fbads_by_country_lookback: 2952000000

  fbads_by_device_platform_tbl_ptrn: '%facebookads%adinsights%device%platform'
  fbads_by_device_platform_tbl_exclude_ptrn: ''
  fbads_by_device_platform_lookback: 2952000000

  fbads_by_gender_tbl_ptrn: '%facebookads%adinsights%gender'
  fbads_by_gender_tbl_exclude_ptrn: ''
  fbads_by_gender_lookback: 2592000000

  fbads_by_gender_age_tbl_ptrn: '%facebookads%adinsights%gender_age'
  fbads_by_gender_age_tbl_exclude_ptrn: ''
  fbads_by_gender_age_lookback: 2592000000

  fbads_by_platform_position_tbl_ptrn: '%facebookads%adinsights%breakdown_publisher_platform_platform_position'
  fbads_by_platform_position_tbl_exclude_ptrn: ''
  fbads_by_platform_position_lookback: 2592000000

  fbads_by_product_id_tbl_ptrn: '%facebookads%adinsights%product_id'
  fbads_by_product_id_tbl_exclude_ptrn: ''
  fbads_by_product_id_lookback: 2592000000

  fbads_by_publisher_platform_tbl_ptrn: '%facebookads%adinsights%breakdown_publisher_platform'
  fbads_by_publisher_platform_tbl_exclude_ptrn: ''
  fbads_by_publisher_platform_lookback: 2592000000

  fbads_by_region_tbl_ptrn: '%facebookads%adinsights%breakdown_region'
  fbads_by_region_tbl_exclude_ptrn: ''
  fbads_by_region_lookback: 2592000000
  
  fbads_campaigns_tbl_ptrn: '%facebookads%campaigns'
  fbads_campaigns_tbl_exclude_ptrn: ''
  fbads_campaigns_lookback: 2592000000 

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  FacebookAds:
    FacebookAds:
      +schema: stg_facebookads